version: '3.8'
services:
  app:
    build: .
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=/opt/app/data/data.db
    volumes:
      - ./uploads:/opt/app/public/uploads
      - ./data:/opt/app/data
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass your_redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 